version: "3.8"

services:
  db:
    image: postgres:12.10
    restart: unless-stopped
    environment:
      - POSTGRES_DB=r99c
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=Asia/Tokyo
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
  app:
    build: .
    ports: [ "3000:3000" ]
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://db/r99c?user=postgres&password=password
      - R99C_REQUIRE_MY_ANSWER=FALSE
    working_dir: /app
    entrypoint: ["java", "-jar", "r99c.jar"]
